-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 20:18:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `idowner` INT NOT NULL,
  `owner_name` VARCHAR(45) NULL,
  `owner_cellphone1` VARCHAR(45) NULL,
  `owner_cellphone2` VARCHAR(45) NULL,
  `owner_email` VARCHAR(45) NULL,
  `owner_nuit` INT NOT NULL,
  `owner_type` VARCHAR(45) NULL,
  `owner_dateLog` DATETIME NULL,
  `owner_balance` DOUBLE NULL,
  PRIMARY KEY (`idowner`),
  UNIQUE INDEX `owner_nuit_UNIQUE` (`owner_nuit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`terminal_rote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`terminal_rote` (
  `idterminal_rote` INT NOT NULL,
  `terminal_rote_date_time` DATETIME NULL,
  `terminal_rote_dateLog` DATETIME NULL,
  PRIMARY KEY (`idterminal_rote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rote` (
  `idrote` INT NOT NULL,
  `rote_name` VARCHAR(45) NULL,
  `terminal_rote_idterminal_rote` INT NOT NULL,
  `rote_dataLog` DATETIME NULL,
  PRIMARY KEY (`idrote`),
  INDEX `fk_rote_terminal_rote1_idx` (`terminal_rote_idterminal_rote` ASC),
  CONSTRAINT `fk_rote_terminal_rote1`
    FOREIGN KEY (`terminal_rote_idterminal_rote`)
    REFERENCES `mydb`.`terminal_rote` (`idterminal_rote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `idcar` VARCHAR(45) NOT NULL,
  `owner_idowner` INT NOT NULL,
  `rote_idrote` INT NOT NULL,
  `car_registration` VARCHAR(45) NOT NULL,
  `car_type` INT NULL,
  `car_dateLog` DATETIME NULL,
  `car_chauffer_name` VARCHAR(45) NULL,
  `car_chauffer_BI` VARCHAR(45) NOT NULL,
  `car_chauffer_balance` DOUBLE NULL,
  INDEX `fk_car_owner_idx` (`owner_idowner` ASC),
  INDEX `fk_car_rote1_idx` (`rote_idrote` ASC),
  PRIMARY KEY (`idcar`),
  UNIQUE INDEX `car_registration_UNIQUE` (`car_registration` ASC),
  CONSTRAINT `fk_car_owner`
    FOREIGN KEY (`owner_idowner`)
    REFERENCES `mydb`.`owner` (`idowner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_rote1`
    FOREIGN KEY (`rote_idrote`)
    REFERENCES `mydb`.`rote` (`idrote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`terminal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`terminal` (
  `idterminal` INT NOT NULL,
  `terminal_name` VARCHAR(45) NULL,
  `terminal_latitude_longitude` VARCHAR(45) NULL,
  `terminal_rote_idterminal_rote` INT NOT NULL,
  `terminal_dateLog` DATETIME NULL,
  PRIMARY KEY (`idterminal`),
  INDEX `fk_terminal_terminal_rote1_idx` (`terminal_rote_idterminal_rote` ASC),
  CONSTRAINT `fk_terminal_terminal_rote1`
    FOREIGN KEY (`terminal_rote_idterminal_rote`)
    REFERENCES `mydb`.`terminal_rote` (`idterminal_rote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passenger` (
  `idpassenger` INT NOT NULL,
  `passenger_name` VARCHAR(45) NULL,
  `passenger_cellphone` VARCHAR(45) NOT NULL,
  `passenger_email` VARCHAR(45) NULL,
  `passenger_password` VARCHAR(45) NULL,
  `passenger_balance` VARCHAR(45) NULL,
  `passenger_dateLog` DATETIME NULL,
  PRIMARY KEY (`idpassenger`),
  UNIQUE INDEX `passenger_cellphone_UNIQUE` (`passenger_cellphone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `idpayment` INT NOT NULL,
  `payment_date_time` DATETIME NULL,
  `payment_coust` DOUBLE NULL,
  `car_idcar` VARCHAR(45) NOT NULL,
  `passenger_idpassenger` INT NOT NULL,
  `payment_dataLog` DATETIME NULL,
  PRIMARY KEY (`idpayment`),
  INDEX `fk_payment_car1_idx` (`car_idcar` ASC),
  INDEX `fk_payment_passenger1_idx` (`passenger_idpassenger` ASC),
  CONSTRAINT `fk_payment_car1`
    FOREIGN KEY (`car_idcar`)
    REFERENCES `mydb`.`car` (`idcar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_passenger1`
    FOREIGN KEY (`passenger_idpassenger`)
    REFERENCES `mydb`.`passenger` (`idpassenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
